language:
    python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - "pip install pipenv"
  - "pipenv install"
  - "pipenv shell"
  - "coverage --version"
# command to run tests
script:
  - python -m "nose" --with-coverage --cov PittAPI/ --with-timer tests/*
notifications:
    email: false
os:
  - linux
