name: auto-test

run-name: ${{ github.actor }} is running unit tests for PittAPI

on: 
  schedule:
    - cron: '00 12 1 * *'

jobs:
  run-test-suite:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: '3.12'


    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run all tests with pytest
        run: |
          pytest --cov=pittapi tests/

    

